#!/usr/bin/env bash

set -e # Exit immediately if a command exits with a non-zero status.
set -x # Print commands and their arguments as they are executed.


COM_CONFIG="bootstrap/install-common-tools.yaml"

if [[ "$OSTYPE" == darwin* ]]; then
    SYS_CONFIG="bootstrap/install-osx.conf.yaml"
elif [[ "$OSTYPE" == linux* ]]; then
    SYS_CONFIG="bootstrap/install-linux.conf.yaml"
else
    echo "[ERROR] unkown OSTYPE: $OSTYPE"
    exit 1
fi

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${COM_CONFIG}" "${@}"

echo "source ~/.dotfiles/runcom/.bash_profile" >> "${HOME}/.bashrc"

# "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${SYS_CONFIG}" "${@}"
